### PR TITLE
Switched to official docker-engine API

### PR DESCRIPTION
**Pull request by aacebedo**
Hi !
This shall solve issues with docker compose discussed in bug #59

### CODE REVIEW

**Comment by james-nesbitt** [comment]
This is a good idea.  It would pay off to no longer be held back by the samalba library.

**Comment by aacebedo** [comment]
Hi. 
As docker switched on golang I think third party go binding are going to be deprecated. That's the reason why I decided to integrate the official binding. 
For your bug I didn't checked the dockerfile only the tests and the Travis. 
I'll check tonight but maybe this is due to the version of golang or godep used in the dockerfile

**Comment by aacebedo** [comment]
Try change the first line and replace 1.4.1 by 1.6.2

**Comment by james-nesbitt** [comment]
Ignore my above error.  The golang version change didn't fix it, but the master branch Dockerfile also doesn't build for me.

**Comment by james-nesbitt** [comment]
@aacebedo why add the vendor folder?  can these dependencies not be build as godeps?

**Comment by aacebedo** [comment]
Godep is a third party tool created to cope with the weak dependency system of golang until 1.6. This version introduced a new standard solution to deal with dependencies which is the vendor folder. The latest version of Godep I used to rebuild the dependencies created the vendor folder because I think they decided to make their tool compatible with this new mechanism

**Comment by aacebedo** [comment]
Corrected the dockerfile @james-nesbitt

**Comment by tonistiigi** [comment]
LGTM

**Pull request merged**
