### PR TITLE
Added handling of MX lookups

### PR DESCRIPTION
**Pull request by tya**

### CODE REVIEW

**Comment by tonistiigi** [comment]
Could you add a test for this?

**Comment by tya** [comment]
I just pushed a couple commits which included MX lookup tests.  I also improved the tests a little.  Rather than just testing for returned resource record counts, the RR type is validated based upon the query RR type.  Travis CI tests pass BTW.

**Comment by tonistiigi** [comment]
Merged. Thanks!

**Comment by kgutwin** [comment]
Perhaps the README could be updated from its current "A records only for now"? I wasn't able to tell by glancing at the patch exactly how the MX feature works.

**Pull request merged**
